name: Trigger Confluence DB Update

on:
  workflow_dispatch:  

jobs:
  run-update-db:
    uses: m-nikolovska-mak-system/reusable-actions-library/.github/workflows/sync-docs-to-confluence.yml@main
    secrets: inherit
