name: Detect File Changes + Notify Teams
on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      watched_file:
        description: "File to watch"
        required: true
        type: string


jobs:
  check_changes:
    name: Check File Changes
    uses: m-nikolovska-mak-system/reusable-actions-library/.github/workflows/3check-file-changes.yml@main
    with:
      watched_files: ${{ github.event.inputs.watched_file }}
      current_tag: ${{ github.event.release.tag_name || github.ref_name }}
      previous_tag: ''

  debug_print:
    name: Debug info
    needs: check_changes
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "changed files:  ${{ needs.check_changes.outputs.changed_files_list }}"
          echo "all changed:    ${{ needs.check_changes.outputs.all_changed_files }}"

  notify_if_changed:
    name: Send Teams Notification
    needs: check_changes
    if: needs.check_changes.outputs.files_changed == 'true'
    uses: m-nikolovska-mak-system/reusable-actions-library/.github/workflows/teams-notifier.yml@main
    with:
      notification_title: "🚨 File Change Detected"
      action_required_message: "Changed: ${{ needs.check_changes.outputs.changed_files_list }}"
      files: ${{ needs.check_changes.outputs.changed_files_list }}
      card_color: "Accent"
    secrets:
      teams_webhook_url: ${{ secrets.TEAMS_WEBHOOK_URL }}
