name: Advanced ACT Test

on:
  workflow_dispatch:
    inputs:
      dry_run:
        description: 'Run without making changes'
        required: false
        default: 'false'
      environment:
        description: 'Target environment'
        required: true
        default: 'dev'

jobs:
  test-matrix:
    name: Matrix Strategy Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [14, 16]
        os: [ubuntu-latest]
    steps:
      - name: Setup Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Print Environment
        run: echo "Running on ${{ matrix.os }} with Node.js ${{ matrix.node }}"

  validate-inputs:
    name: Input Validation
    runs-on: ubuntu-latest
    steps:
      - name: Check dry-run input
        run: |
          if [[ "${{ github.event.inputs.dry_run }}" == "true" ]]; then
            echo "Dry run mode enabled"
          else
            echo "Executing real changes"
          fi

  use-secrets:
    name: Secrets and Env Vars
    runs-on: ubuntu-latest
    env:
      MY_SECRET: ${{ secrets.MY_SECRET }}
    steps:
      - name: Print secret (simulated)
        run: echo "Secret is set (not printing for safety)"

  conditional-step:
    name: Conditional Execution
    runs-on: ubuntu-latest
    steps:
      - name: Run only in dev
        if: github.event.inputs.environment == 'dev'
        run: echo "Running in development environment"

  concurrency-test:
    name: Concurrency Control
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.event.inputs.environment }}
      cancel-in-progress: true
    steps:
      - name: Simulate long task
        run: sleep 10

  post-run-cleanup:
    name: Cleanup
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        run: echo "Setting up resources"

      - name: Cleanup
        if: always()
        run: echo "Cleaning up resources"
