name: Sync Docs to Confluence
on:
#  push:
 #   branches:
  #    - main
   # paths:
    #  - 'docs/**'

#  pull_request:
 #   paths:
  #    - 'docs/**'
    workflow_dispatch:


jobs:
  sync-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Publish Docs to Confluence
        uses: Bhacaz/docs-as-code-confluence@v3
        with:
          folder: docs
          username: ${{ secrets.CONFLUENCE_USER }}
          password: ${{ secrets.CONFLUENCE_API_TOKEN }}
          confluence-base-url: https://mihaelanikolovska183014.atlassian.net/wiki
          space-key: DS
          parent-page-id: 2785550
