name: Sync Docs to Confluence

on:
#  push:
 #   branches:
  #    - main
   # paths:
    #  - 'docs/**'
    workflow_dispatch:

jobs:
  sync-docs:
    runs-on: ubuntu-latest
    # Prevent concurrent syncs
    concurrency:
      group: confluence-sync
      cancel-in-progress: false
    
    permissions:
      contents: read
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2  
      
      - name: Check for actual doc changes
        id: check_changes
        run: |
          if git diff HEAD^ HEAD --quiet -- docs/; then
            echo "changed=false" >> $GITHUB_OUTPUT
            echo "No actual changes in docs/"
          else
            echo "changed=true" >> $GITHUB_OUTPUT
            echo "Changes detected in docs/"
          fi
      
      - name: Verify docs folder exists
        if: steps.check_changes.outputs.changed == 'true'
        run: |
          if [ ! -d "docs" ]; then
            echo "Error: docs/ folder not found"
            exit 1
          fi
          if [ -z "$(ls -A docs)" ]; then
            echo "Error: docs/ folder is empty"
            exit 1
          fi
      
      - name: Publish Docs to Confluence
        if: steps.check_changes.outputs.changed == 'true'
        uses: Bhacaz/docs-as-code-confluence@v3
        with:
          folder: docs
          username: ${{ secrets.CONFLUENCE_USER }}
          password: ${{ secrets.CONFLUENCE_API_TOKEN }}
          confluence-base-url: https://mihaelanikolovska183014.atlassian.net/wiki
          space-key: DS
          parent-page-id: 2785550
        timeout-minutes: 10
      
      - name: Notify on failure
        if: failure()
        run: |
          echo "::error::Confluence sync failed. Check the logs above for details."
          echo "::notice::You may need to manually sync docs to Confluence"
