name: Build Windows Installer

on:
  workflow_call:
    inputs:
      jar-key:
        description: 'Cache key for the JAR file'
        type: string
        required: true
      release_tag:
        type: string
        description: 'Tag name of the release'
        required: true
        
jobs:
  build-installer:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.release_tag }}

      - name: Download built JAR from previous workflow
        uses: actions/download-artifact@v4
        with:
          name: app-jar
          path: build/libs

      - name: Verify JAR
        run: dir build\libs

      - name: Install Inno Setup
        run: choco install innosetup --no-progress -y

      - name: Build setup.exe
        run: |
          "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" .github\setup-script.iss

      - name: Upload setup.exe as artifact
        uses: actions/upload-artifact@v4
        with:
          name: setup-installer
          path: output/OneProjectWed-Setup.exe

      - name: Check output folder
        run: dir output   

      - name: Upload setup.exe to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: output/OneProjectWed-Setup.exe
          tag_name: ${{ github.event.inputs.release_tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
