# ========================================
# Build & Release Java Application Workflow
# ========================================
# Version: 3.0
# Purpose: Orchestrates full build→validate→package→release pipeline
# Maintainer: Platform Engineering Team
# Last Updated: 2025-01-21
#
# This workflow automates:
# 1. Java JAR compilation via Gradle
# 2. Artifact validation and verification
# 3. Windows installer creation using Inno Setup
# 4. GitHub Release artifact publishing
# 5. Microsoft Teams notifications (success/failure)
#
# Triggers:
# - Automatic: When GitHub Release is created
# - Manual: Via Actions UI with optional parameter overrides
# ========================================

name: Build & Release Java App

# ========== TRIGGER CONFIGURATION ==========
on:
  # Manual trigger - allows developers to test builds with custom parameters
  workflow_dispatch:
    inputs:
      java_version:
        description: 'Java version to use for compilation'
        required: false
        default: '17'
        type: string
      java_distribution:
        description: 'Java distribution (temurin, corretto, zulu)'
        required: false
        default: 'temurin'
        type: string
      gradle_task:
        description: 'Gradle task to execute (jar, build, shadowJar)'
        required: false
        default: 'jar'
        type: string
  
  # Automatic trigger - fires whenever a release is created
  # This is the primary production trigger
#  release:
 #   types: [created]

# ========== CONCURRENCY SETTINGS ==========
# Prevents multiple builds for the same release from running simultaneously
# Cancellation disabled to avoid killing in-progress production releases
concurrency:
  group: ${{ github.workflow }}-${{ github.event.release.tag_name || github.run_id }}
  cancel-in-progress: false

# ========== PIPELINE JOBS ==========
jobs:
  # ─────────────────────────────────────
  # STAGE 1: BUILD JAR
  # ─────────────────────────────────────
  # Compiles Java application via Gradle
  # Outputs: JAR file + cache key for downstream jobs
  # Duration: ~2-5 minutes
  # Failure: Blocks entire pipeline
  build_jar:
    name: Build JAR
    uses: m-nikolovska-mak-system/reusable-actions-library/.github/workflows/build-jar.yml@main
    with:
      # Release version from GitHub Release tag (e.g., v1.2.3)
      release_tag: ${{ github.event.release.tag_name }}
      
      # Gradle task - customizable via workflow_dispatch
      # Defaults to 'jar' but can be overridden to 'shadowJar', 'build', etc.
      gradle_task: ${{ inputs.gradle_task || 'jar' }}
      
      # Java version - customizable via workflow_dispatch
      # Supports: 11, 17, 21, etc.
      java_version: ${{ inputs.java_version || '17' }}
      
      # Java distribution - customizable via workflow_dispatch
      # Supports: temurin (Eclipse), corretto (AWS), zulu (Azul)
      java_distribution: ${{ inputs.java_distribution || 'temurin' }}

  # ─────────────────────────────────────
  # STAGE 2A: DETECT SETUP SCRIPT
  # ─────────────────────────────────────
  # Validates that Inno Setup (.iss) configuration exists
  # Outputs: setup_script path for installer creation
  # Duration: ~30 seconds
  # Failure: Blocks installer build
  detect_iss:
    name: Detect Setup Script
    uses: m-nikolovska-mak-system/reusable-actions-library/.github/workflows/detect-setup-script.yml@main
    with:
      # File pattern to search for Inno Setup configuration
      pattern: "**/*.iss"
      
      # Fail if no .iss file found (strict validation)
      # Set to false if .iss is optional in your repo
      fail_if_missing: true

  # ─────────────────────────────────────
  # STAGE 2B: VALIDATE BUILD OUTPUTS
  # ─────────────────────────────────────
  # Sanity checks on JAR build to catch failures early
  # Prevents unnecessary installer build on bad artifacts
  # Duration: ~1 minute
  # Failure: Blocks installer build
  validate_inputs:
    name: Validate JAR cache key
    needs: build_jar  # Waits for build_jar to complete
    runs-on: ubuntu-latest
    steps:
      - name: Check jar_cache_key
        run: |
          # Verify JAR cache key exists and is not empty
          # Cache key used by downstream jobs to retrieve artifacts
          if [ -z "${{ needs.build_jar.outputs.jar_cache_key }}" ]; then
            echo "::error::JAR cache key is empty - build may have failed silently"
            exit 1
          fi
          echo "✓ JAR cache key validated: ${{ needs.build_jar.outputs.jar_cache_key }}"

  # ─────────────────────────────────────
  # STAGE 3: BUILD WINDOWS INSTALLER
  # ─────────────────────────────────────
  # Creates .exe installer from JAR using Inno Setup
  # Outputs: installer artifact (e.g., Setup-v1.2.3.exe)
  # Duration: ~3-5 minutes
  # Dependencies: Requires build_jar, detect_iss, and validate_inputs to succeed
  build_installer:
    name: Build Windows Installer
    needs: [build_jar, detect_iss, validate_inputs]  # Wait for all previous stages
    uses: m-nikolovska-mak-system/reusable-actions-library/.github/workflows/build-installer.yml@main
    with:
      # Inno Setup configuration file (output from detect_iss)
      setup_script: ${{ needs.detect_iss.outputs.setup_script }}
      
      # JAR file path (output from build_jar)
      jar_path: ${{ needs.build_jar.outputs.jar_path }}
      
      # Gradle cache key for retrieving JAR artifact
      jar_cache_key: ${{ needs.build_jar.outputs.jar_cache_key }}
      
      # Application name (auto-populated from repository name)
      app_name: ${{ github.event.repository.name }}
      
      # Application version (from release tag, e.g., v1.2.3)
      app_version: ${{ github.event.release.tag_name }}
      
      # Installer output filename pattern
      output_name: "Setup-${{ github.event.release.tag_name }}"

  # ─────────────────────────────────────
  # STAGE 4: UPLOAD RELEASE ASSET
  # ─────────────────────────────────────
  # Publishes installer to GitHub Release as downloadable artifact
  # Users download from: github.com/repo/releases/tag/vX.Y.Z
  # Duration: ~1 minute
  upload_release:
    name: Upload Release Asset
    needs: build_installer  # Waits for installer creation
    uses: m-nikolovska-mak-system/reusable-actions-library/.github/workflows/upload-release.yml@main
    with:
      # GitHub Release tag (e.g., v1.2.3)
      tag_name: ${{ github.event.release.tag_name }}
      
      # Installer artifact name to upload
      artifact_name: ${{ needs.build_installer.outputs.installer_artifact_name }}

  # ─────────────────────────────────────
  # STAGE 5A: NOTIFY SUCCESS
  # ─────────────────────────────────────
  # Sends success notification to Microsoft Teams
  # Only runs if ALL jobs succeed AND trigger is release event
  # Duration: ~30 seconds
  notify_success:
    name: Notify Success
    needs: [build_jar, detect_iss, validate_inputs, build_installer, upload_release]
    # Only notify on success AND if triggered by release event
    if: success() && github.event_name == 'release'
    uses: m-nikolovska-mak-system/reusable-actions-library/.github/workflows/teams-notifier.yml@main
    with:
      notification_title: "✅ Build & Release Succeeded!"
      action_required_message: "Release ${{ github.event.release.tag_name }} is ready. View: ${{ github.event.release.html_url }}"
    secrets:
      teams_webhook_url: ${{ secrets.TEAMS_WEBHOOK_URL }}

  # ─────────────────────────────────────
  # STAGE 5B: NOTIFY FAILURE
  # ─────────────────────────────────────
  # Sends failure notification to Microsoft Teams with debug info
  # Triggered on ANY job failure
  # Duration: ~30 seconds
  notify_failure:
    name: Notify Failure
    needs: [build_jar, detect_iss, validate_inputs, build_installer, upload_release]
    # Only notify on failure (regardless of trigger type)
    if: failure()
    uses: m-nikolovska-mak-system/reusable-actions-library/.github/workflows/teams-notifier.yml@main
    with:
      notification_title: "🚨 Build & Release Failed!"
      action_required_message: |
        Check logs: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        Release: ${{ github.event.release.tag_name || 'N/A' }}
    secrets:
      teams_webhook_url: ${{ secrets.TEAMS_WEBHOOK_URL }}
