name: OVA TREBA DA RABOTI Build JAR

on:
  # release:
   # types: [created]
  
  workflow_dispatch:
    inputs:
      ref:
        description: 'Branch or tag to build'
        required: false
        default: 'main'

jobs:
  build-jar:
    runs-on: ubuntu-latest
    outputs:
      jar-cache-key: ${{ steps.cache-key.outputs.key }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name || github.event.inputs.ref || 'main' }}
      
      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      
      - name: Make Gradle wrapper executable
        run: chmod +x gradlew
      
      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      
      - name: Build JAR with Gradle
        run: ./gradlew clean jar --no-daemon


      - name: Upload JAR as artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: build/libs/*.jar
      
      - name: Generate cache key
        id: cache-key
        run: echo "key=jar-${{ github.sha }}-${{ github.run_number }}" >> $GITHUB_OUTPUT
      
      - name: Cache built JAR
        uses: actions/cache/save@v3
        with:
          path: build/libs/*.jar
          key: ${{ steps.cache-key.outputs.key }}
  
  build-installer:
    needs: build-jar
    runs-on: windows-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name || github.event.inputs.ref || 'main' }}
      
      - name: Download JAR artifact
        uses: actions/download-artifact@v4
        with:
          name: app-jar
          path: build/libs

      - name: Rename JAR to App.jar
        run: |
          $jar = Get-ChildItem build\libs\*.jar | Select-Object -First 1
          if ($jar.Name -ne "App.jar") {
            Rename-Item $jar.FullName -NewName "App.jar"
          }
            
      - name: Verify JAR
        run: dir build\libs
      
      - name: Install Inno Setup
        run: choco install innosetup --no-progress -y
      
      - name: Build setup.exe
        run: |
          & "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" setup-script.iss
      
      - name: Check output folder
        run: dir output
      
      - name: Upload setup.exe to GitHub Release
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v2
        with:
          files: output/OneProjectWed-Setup.exe
          tag_name: ${{ github.event.release.tag_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Upload setup.exe as artifact (for workflow_dispatch)
        if: github.event_name == 'workflow_dispatch'
        uses: actions/upload-artifact@v4
        with:
          name: setup-installer
          path: output/OneProjectWed-Setup.exe
              
