name: Confluence DB test
on:
  workflow_dispatch:
jobs:
  create-row:
    runs-on: ubuntu-latest
    env:
      BASE: ${{ vars.CONFLUENCE_BASE }}
      EMAIL: ${{ secrets.CONFLUENCE_USER }}
      TOKEN: ${{ secrets.CONFLUENCE_API_TOKEN }}
      DB_ID: ${{ secrets.CONFLUENCE_DB_PAGE_ID }}
    steps:
      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq
      
      - name: Show environment (for debug)
        run: |
          echo "BASE: $BASE"
          echo "DB_ID: $DB_ID"
      
      - name: List available databases (diagnose)
        run: |
          echo "=== Available Databases ==="
          curl -s -u "$EMAIL:$TOKEN" "$BASE/wiki/api/v2/databases" | jq . || echo "Failed to list databases"
      
      - name: Get database metadata
        run: |
          echo "=== Database Metadata for $DB_ID ==="
          curl -s -u "$EMAIL:$TOKEN" "$BASE/wiki/api/v2/databases/$DB_ID" | jq . || echo "Failed to get database metadata"
      
      - name: Try listing rows
        run: |
          echo "=== First row from database ==="
          curl -s -u "$EMAIL:$TOKEN" "$BASE/wiki/api/v2/databases/$DB_ID/rows?limit=1" | jq . || echo "Failed to list rows"
      
      - name: Create test row
        run: |
          echo "=== Creating test row ==="
          curl -s -u "$EMAIL:$TOKEN" \
            -H "Content-Type: application/json" \
            -X POST "$BASE/wiki/api/v2/databases/$DB_ID/rows" \
            -d '{
              "values": {
                "Name": "Test from GitHub",
                "Status": "Active"
              }
            }' | jq . || echo "Row creation failed - check column names"
