name: Dependency Health

on: 
  workflow_dispatch:

jobs:
  check-deps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Check package.json exists
        run: |
          if [ -f package.json ]; then
            echo "✅ package.json found"
            cat package.json | jq '.dependencies // {}, .devDependencies // {}' || true
          else
            echo "ℹ️  No package.json - skipping"
            exit 0
          fi
      
      - name: Check for package-lock.json
        run: |
          if [ -f package-lock.json ]; then
            echo "✅ package-lock.json present"
          else
            echo "⚠️  No package-lock.json - dependencies not locked"
          fi
