name: Generate Workflow Docs

on:
  workflow_dispatch:
#  push:
#    paths:
#      - ".github/workflows/*.yml"
#      - ".github/workflows/*.yaml"

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Find all workflow files
        id: list
        run: |
          files=$(ls .github/workflows/*.yml .github/workflows/*.yaml 2>/dev/null || true)
          echo "files<<EOF" >> $GITHUB_OUTPUT
          echo "$files" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install js-yaml

      - name: Generate docs
        run: |
          mkdir -p docs/workflows
      
          for file in .github/workflows/*.yml .github/workflows/*.yaml; do
            # Skip if no such file exists (glob failed)
            [ -e "$file" ] || continue
      
            name=$(basename "$file")
            name="${name%.*}"
      
            echo "Generating docs for $file → docs/workflows/${name}.md"
      
            node .github/scripts/generate-readme.js "$file" "docs/workflows/${name}.md"
          done


      - name: Commit documentation
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "auto: update workflow documentation"
          file_pattern: docs/workflows/*.md
