name: Generate workflow docs

on:
  workflow_dispatch:
    inputs:
      filename:
        description: 'Path to the workflow or action file (relative to repo root)'
        required: true
        default: .github/actions/lint-check/action.yml
      output:
        description: 'Output markdown path (relative to repo root)'
        required: false
        default: docs/workflows.md
     

jobs:
  build-doc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generate README with auto-doc
        uses: tj-actions/auto-doc@v3
        with:
          file: ${{ github.event.inputs.filename }}
          output: ${{ github.event.inputs.output }}
          # optional: include_yaml: true

      - name: Commit generated docs
        if: ${{ steps.generate_doc_outcome != 'failure' }}
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions[bot]
          author_email: 41898282+github-actions[bot]@users.noreply.github.com
          message: "chore(docs): update workflow docs for ${{ github.event.inputs.filename }}"
          add: ${{ github.event.inputs.output }}
