name: Generate README
on:
  workflow_dispatch:

jobs:
  generate-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Generate README
        uses: bitflight-devops/github-action-readme-generator@v1
        with:
          action: .github/workflows/hello.yml
          readme: AUTO_README.md
          save: false
