name: Test – dispatch with inputs
on:
  workflow_dispatch:
    inputs:
      message:
        description: "Say hi from wf dispatch test hello"
        required: true
        type: string

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello"
