name: Main Build and Release

on:
 # release:
  #  types: [created]

jobs:
  build_jar:
    uses: ./.github/workflows/build-jar.yml
    with:
      release_tag: ${{ github.event.release.tag_name }}

  detect_iss:
    uses: ./.github/workflows/detect-setup-script.yml

  build_installer:
    needs: [build_jar, detect_iss]
    uses: ./.github/workflows/build-installer.yml
    with:
        jar_cache_key: ${{ needs.build_jar.outputs.jar_cache_key }}
        release_tag: ${{ github.event.release.tag_name }}
        setup_script: ${{ needs.detect_iss.outputs.setup_script }}
        app_name: ${{ github.event.repository.name }}
        app_version: ${{ github.event.release.tag_name }}
        output_name: "Setup-${{ github.event.release.tag_name }}"

  upload_release:
    needs: build_installer
    uses: ./.github/workflows/upload-release.yml
    with:
      artifact_path: ${{ needs.build_installer.outputs.installer_file }}
      tag_name: ${{ github.event.release.tag_name }}
   
  
  notify-on-failure:
    needs: [build_jar, build_installer, upload_release]
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: Report failure
        run: |
          echo "❌ Workflow failed"
          echo "Failed jobs: ${{ toJSON(needs) }}"
