name: ðŸ“ Auto-Generate Workflow Documentation

on:
   workflow_call:  # Can be called by orchestrator
    outputs:
      changed_readmes:
        description: "List of changed README files"
        value: ${{ jobs.collect-changes.outputs.readmes }}
   workflow_dispatch: 
   pull_request:
      branches-ignore:
        - 'auto-doc/**' 
      paths:
        - ".github/workflows/*.yml"
        - ".github/workflows/*.yaml"

permissions:
  contents: write
  pull-requests: write

env:
  GITHUB_USER_TOKEN: ${{ secrets.USER_TOKEN }}
  GITHUB_USER_EMAIL: "email@company.net"
  GITHUB_USER_NAME: "user1"

jobs:
  detect-changes:
    name: ðŸ” Detect Changed Workflows
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.prep_matrix.outputs.matrix }}
      has_changes: ${{ steps.prep_matrix.outputs.has_changes }}
      pr_source_branch: ${{ steps.get_source_branch.outputs.pr_source_branch }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Detect changed workflows
        id: detect
        uses: tj-actions/changed-files@v44
        with:
          files: |
            .github/workflows/*.yml
            .github/workflows/*.yaml
            !.github/workflows/new-ci-readme-docs.yml

      - name: Debug - Print all changed files
        run: |
          echo "Any changed: ${{ steps.detect.outputs.any_changed }}"
          echo "Changed files:"
          for f in ${{ steps.detect.outputs.all_changed_files }}; do
            echo " - $f"
          done    

      - name: Stop if no workflow changes
        if: steps.detect.outputs.any_changed == 'false'
        run: echo "No workflow changes detected." && exit 0

      - name: Prepare matrix JSON
        id: prep_matrix
        run: |
          if [ "${{ steps.detect.outputs.any_changed }}" == "false" ]; then
            echo "has_changes=false" >> $GITHUB_OUTPUT
            echo "matrix=[]" >> $GITHUB_OUTPUT  
            echo "âš ï¸ No workflow changes detected."
            exit 0
          fi
        
          json="[]"
          for f in ${{ steps.detect.outputs.all_changed_files }}; do
            base=$(basename "$f")
            base="${base%.yml}"
            base="${base%.yaml}"
            json=$(echo "$json" | jq --arg wf "$f" --arg b "$base" '. += [{"workflow":$wf,"basename":$b}]')
          done
          
          count=$(echo "$json" | jq 'length')
          if [ "$count" -eq 0 ]; then
            echo "has_changes=false" >> $GITHUB_OUTPUT
            echo "matrix=[]" >> $GITHUB_OUTPUT          # âœ… empty array
            echo "âš ï¸ No valid workflows to process."
          else
            echo "has_changes=true" >> $GITHUB_OUTPUT
            echo "matrix=$(echo "$json" | jq -c '.')" >> $GITHUB_OUTPUT
            echo "âœ… Matrix prepared with $count workflows"
          fi

      - name: Get PR source branch
        id: get_source_branch
        run: echo "pr_source_branch=${{ github.head_ref }}" >> $GITHUB_OUTPUT

  update-doc:
    name: ðŸ“ Generate & Update Workflow READMEs
    needs: detect-changes
    if: needs.detect-changes.outputs.has_changes == 'true'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        item: ${{ fromJson(needs.detect-changes.outputs.matrix) }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ env.GITHUB_USER_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"


      - name: Cache Python dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-pyyaml

      
      - name: Install dependencies
        run: pip install pyyaml

      - name: Ensure docs directory exists
        run: mkdir -p docs

      # ------------------------------
      #   1. Create missing README from template
      # ------------------------------
      - name: Create missing README if needed
        id: create_readme
        run: |
          TEMPLATE="docs/README-reusable.md"
          README="docs/README-${{ matrix.item.basename }}.md"

          if [ ! -f "$README" ]; then
            echo "Creating missing README: $README"
            cp "$TEMPLATE" "$README"
            sed -i "/^## Usage$/a Documentation for workflow ${{ matrix.item.basename }}." "$README"
          fi

      # ------------------------------
      #   2. Run *your Python extractor*
      # ------------------------------
      - name: Generate documentation (Python extractor)
        run: |
          python3 scripts/extract-v2.py \
            "${{ matrix.item.workflow }}" \
            "docs/README-${{ matrix.item.basename }}.md"


      - name: Set README path output
        id: readme_path
        run: echo "path=docs/README-${{ matrix.item.basename }}.md" >> $GITHUB_OUTPUT

      # ------------------------------
      #   3. Verify README changes
      # ------------------------------
      - name: Verify README changed
        id: verify
        uses: tj-actions/verify-changed-files@v19
        with:
          files: docs/README-${{ matrix.item.basename }}.md

      # ------------------------------
      #   4. Create PR (only if changed)
      # ------------------------------
      - name: Create Pull Request for Documentation Update
        if: steps.verify.outputs.files_changed == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "docs: auto-update README for ${{ matrix.item.basename }}"
          title: "docs: auto-update README for ${{ matrix.item.basename }}"
          body: |
            This PR updates the documentation for:
            **${{ matrix.item.basename }}**
            ðŸ”— Changes detected in commit: [${{ github.sha }}](${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }})

          branch: "auto-doc/update-readme-${{ matrix.item.basename }}"
          committer: ${{ env.GITHUB_USER_NAME }} <${{ env.GITHUB_USER_EMAIL }}>
          token: ${{ env.GITHUB_USER_TOKEN }}
          base: ${{ needs.detect-changes.outputs.pr_source_branch || github.event.pull_request.base.ref }}
          delete-branch: true


  collect-changes:
    name: ðŸ“¦ Collect Changed READMEs
    needs: update-doc
    if: needs.detect-changes.outputs.has_changes == 'true'
    runs-on: ubuntu-latest
    outputs:
      readmes: ${{ steps.collect.outputs.files }}
    steps:
      - name: Collect all README paths
        id: collect
        run: |
          # This will be used by the next workflow
          echo "files=docs/README-*.md" >> $GITHUB_OUTPUT
