name: Publish to Confluence

on:
  workflow_call:
    inputs:
      space:
        required: true
        type: string
      title:
        required: true
        type: string
      file:
        required: true
        type: string
      parent_id:
        required: false
        type: string
      page_id:
        required: false
        type: string
    secrets:
      confluence_user:
        required: true
      confluence_token:
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Read file content
        id: filecontent
        run: |
          CONTENT=$(cat "${{ inputs.file }}" | sed 's/"/\\"/g')
          echo "content=$CONTENT" >> $GITHUB_OUTPUT

      #################################################
      # 1️⃣ DETERMINE IF PAGE EXISTS (if page_id is not provided)
      #################################################

      - name: Find page by title (if no page_id is provided)
        id: lookup
        if: ${{ !inputs.page_id }}
        run: |
          SEARCH=$(curl -s -u "${{ secrets.confluence_user }}:${{ secrets.confluence_token }}" \
            --get \
            --data-urlencode "title=${{ inputs.title }}" \
            --data-urlencode "spaceKey=${{ inputs.space }}" \
            "https://mihaelanikolovska183014.atlassian.net/wiki/rest/api/content")

          PAGE_ID=$(echo "$SEARCH" | jq -r '.results[0].id // empty')
          echo "found_page_id=$PAGE_ID" >> $GITHUB_OUTPUT

      #################################################
      # 2️⃣ CREATE PAGE IF NOT FOUND
      #################################################

      - name: Create page if missing
        id: create
        if: ${{ !inputs.page_id && steps.lookup.outputs.found_page_id == '' }}
        run: |
          echo "Page does not exist. Creating new page..."

          JSON=$(cat <<EOF
          {
            "type": "page",
            "title": "${{ inputs.title }}",
            "space": { "key": "${{ inputs.space }}" },
            "ancestors": [
              { "id": "${{ inputs.parent_id || '' }}" }
            ],
            "body": {
              "storage": {
                "value": "${{ steps.filecontent.outputs.content }}",
                "representation": "storage"
              }
            }
          }
          EOF
          )

          RESULT=$(curl -s -u "${{ secrets.confluence_user }}:${{ secrets.confluence_token }}" \
            -X POST \
            -H "Content-Type: application/json" \
            -d "$JSON" \
            "https://mihaelanikolovska183014.atlassian.net/wiki/rest/api/content/")

          PAGE_ID=$(echo "$RESULT" | jq -r '.id')
          echo "page_id=$PAGE_ID" >> $GITHUB_OUTPUT

      #################################################
      # 3️⃣ UPDATE PAGE IF IT EXISTS
      #################################################

      - name: Determine final page ID
        id: finalid
        run: |
          if [ -n "${{ inputs.page_id }}" ]; then
            echo "page_id=${{ inputs.page_id }}" >> $GITHUB_OUTPUT
          elif [ -n "${{ steps.lookup.outputs.found_page_id }}" ]; then
            echo "page_id=${{ steps.lookup.outputs.found_page_id }}" >> $GITHUB_OUTPUT
          else
            echo "page_id=${{ steps.create.outputs.page_id }}" >> $GITHUB_OUTPUT
          fi

      - name: Get current version
        id: version
        run: |
          META=$(curl -s -u "${{ secrets.confluence_user }}:${{ secrets.confluence_token }}" \
            "https://mihaelanikolovska183014.atlassian.net/wiki/rest/api/content/${{ steps.finalid.outputs.page_id }}?expand=version")

          VERSION=$(echo "$META" | jq -r '.version.number')
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Update page
        run: |
          NEW_VERSION=$(( ${{ steps.version.outputs.version }} + 1 ))

          JSON=$(cat <<EOF
          {
            "id": "${{ steps.finalid.outputs.page_id }}",
            "type": "page",
            "title": "${{ inputs.title }}",
            "space": { "key": "${{ inputs.space }}" },
            "version": {
              "number": $NEW_VERSION
            },
            "body": {
              "storage": {
                "value": "${{ steps.filecontent.outputs.content }}",
                "representation": "storage"
              }
            }
          }
          EOF
          )

          curl -s -u "${{ secrets.confluence_user }}:${{ secrets.confluence_token }}" \
            -X PUT \
            -H "Content-Type: application/json" \
            -d "$JSON" \
            "https://mihaelanikolovska183014.atlassian.net/wiki/rest/api/content/${{ steps.finalid.outputs.page_id }}"
