name: Sync Changed Files to Platform Repo

on:
  release:
    types: [published]

jobs:
  sync-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Product Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # IMPORTANT - lets us compare tags
          path: product

      - name: Checkout Platform Repo
        uses: actions/checkout@v4
        with:
          repository: m-nikolovska-mak-system/platform-repo
          token: ${{ secrets.PLATFORM_PAT }}
          fetch-depth: 0
          path: platform

      - name: Detect Changed Files
        working-directory: product
        run: |
          git fetch --tags

          LATEST="${{ github.event.release.tag_name }}"
          PREVIOUS=$(git describe --tags --abbrev=0 ${LATEST}^)

          echo "Previous tag: $PREVIOUS"
          echo "Latest tag: $LATEST"

          git diff --name-only $PREVIOUS $LATEST > changed_files.txt

          echo "CHANGED_FILES<<EOF" >> $GITHUB_ENV
          cat changed_files.txt >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Sync Changed Files to Platform Repo
        run: |
          echo "Changed files:"
          echo "$CHANGED_FILES"

          cd product

          while IFS= read -r f; do
            mkdir -p "../platform/$(dirname "$f")"
            cp "$f" "../platform/$f"
            echo "Copied: $f"
          done <<< "$CHANGED_FILES"

      - name: Commit Changes to Platform Repo
        working-directory: platform
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add .
          if git diff --staged --quiet; then
            echo "No changes to commit"
            exit 0
          fi

          git commit -m "Sync from release ${{ github.event.release.tag_name }}"
          git push

      - name: Tag Release in Platform Repo
        working-directory: platform
        run: |
          git tag ${{ github.event.release.tag_name }}
          git push origin ${{ github.event.release.tag_name }}
