name: Secret Scanner

on: 
  workflow_dispatch:

jobs:
  scan-secrets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Scan for potential secrets
        run: |
          echo "🔍 Scanning for potential secrets..."
          
          # Common secret patterns
          issues=0
          
          # Check for API keys
          if grep -r "api[_-]key.*=.*['\"][a-zA-Z0-9]\{20,\}" . --exclude-dir=.git 2>/dev/null; then
            echo "⚠️  Potential API key found"
            issues=$((issues+1))
          fi
          
          # Check for AWS keys
          if grep -r "AKIA[0-9A-Z]\{16\}" . --exclude-dir=.git 2>/dev/null; then
            echo "⚠️  Potential AWS key found"
            issues=$((issues+1))
          fi
          
          # Check for private keys
          if grep -r "BEGIN.*PRIVATE KEY" . --exclude-dir=.git 2>/dev/null; then
            echo "⚠️  Private key found"
            issues=$((issues+1))
          fi
          
          if [ $issues -eq 0 ]; then
            echo "✅ No obvious secrets detected"
          else
            echo "❌ Found $issues potential secret(s)"
            exit 1
          fi
