name: Test Tag Push

on:
 # push:
  #  tags:
   #   - '*'  
   workflow_dispatch: 

jobs:
  print-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Show pushed tag
        run: |
          echo "Tag pushed: ${{ github.event.ref }}"
