name: Auto Sync Docs

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'

jobs:
  sync:
    uses: m-nikolovska-mak-system/reusable-actions-library/.github/workflows/sync-docs-to-confluence.yml@main
    with:
      space-key: DS
      parent-page-id: 2785550
    secrets:
      confluence_user: ${{ secrets.CONFLUENCE_USER }}
      confluence_api_token: ${{ secrets.CONFLUENCE_API_TOKEN }}
