name: Test Token
on: push

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Call GitHub API
        run: |
          curl -H "Authorization: Bearer ${{ github.token }}" \
               -H "Accept: application/vnd.github+json" \
               https://api.github.com/repos/${{ github.repository }}

      - name: Test write
        run: |
          echo "Hello" >> test.txt
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "test write"
          git push
