name: Basic Workflow HELLO I AM TESTING HERE!!

on:
#  push:
 #   branches: [ "main", "dev" ]
 #   paths:
 #     - "src/**"
  #    - "!src/ignore/**"
#  pull_request:
 #   types: [opened, synchronize, reopened]
 workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: echo "Building..."
