name: Test Teams Notification

on:
  workflow_dispatch:

jobs:
  send-notification:
    runs-on: ubuntu-latest
    steps:
      - name: Send test Microsoft Teams notification
        env:
          TEAMS_WEBHOOK_URL: ${{ secrets.TEAMS_WEBHOOK_URL }}
        run: |
          PAYLOAD='{"text": "Hello from act! This is a test notification."}'

          echo "📤 Sending notification to Teams..."
          HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" -H "Content-Type: application/json" -d "$PAYLOAD" "$TEAMS_WEBHOOK_URL")
          if [ "$HTTP_CODE" = "200" ] || [ "$HTTP_CODE" = "202" ]; then
            echo "✅ Teams notification sent successfully!"
          else
            echo "❌ Error: Teams webhook failed with status $HTTP_CODE"
            exit 1
          fi
