name: Test Static README

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run generator
        run: |
           python3 ./scripts/generate_static_readme.py \
            --template ./docs/template-simple.md \
            --output ./docs/README-test.md

      - name: Show diff
        run: git diff --color

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/README-test.md
          git commit -m "Update static README" || echo "ℹ️ No changes to commit"
          git push
