
name: Test Create Jira Issue

on:
  workflow_dispatch:
    inputs:
      project_key:
        description: "Jira project key"
        required: true
        type: string
      summary:
        description: "Summary"
        required: true
        type: string
      description:
        description: "Description"
        required: false
        type: string
   
jobs:
  create_issue:
    uses: m-nikolovska-mak-system/reusable-actions-library/.github/workflows/create-jira-issue.yml@main
    with:
      project_key: ${{ inputs.project_key }}
      summary: ${{ inputs.summary }}
      description: ${{ inputs.description }}
    secrets:
      JIRA_EMAIL: ${{ secrets.JIRA_USER }}
      JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
      JIRA_URL: ${{ secrets.JIRA_BASE_URL }}
