name: Test Composite Action

on:
  workflow_dispatch:

jobs:
  test-readme-validator:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run README Validator
        uses: ./actions/readme-validator
        with:
          input_file: README.md