name: Update README with Action Docs
on:
#  push:
#    branches:
 #     - main
 workflow_dispatch: 

jobs:
  update-doc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run auto-doc
        uses: tj-actions/auto-doc@v3
        with:
          filename: action.yml       
