name: ðŸ“ Auto-generate workflow READMEs v5

on:
  workflow_dispatch:
 # pull_request:
   # paths:
  #    - ".github/workflows/*.yml"

permissions:
  contents: write
  pull-requests: write

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.handle_matrix.outputs.matrix }}
      has_changes: ${{ steps.handle_matrix.outputs.has_changes }}
      pr_source_branch: ${{ steps.get_source_branch.outputs.pr_source_branch }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Detect changed workflow files (PR only)
        if: github.event_name == 'pull_request'
        id: detect
        uses: tj-actions/changed-files@v44
        with:
          files: |
            .github/workflows/*.yml
            !.github/workflows/workflow_docs_v2.yml

      - name: Get all workflow files (manual dispatch)
        if: github.event_name == 'workflow_dispatch'
        id: all_workflows
        run: |
          files=$(find .github/workflows -name "*.yml" -not -name "workflow_docs_v2.yml" | tr '\n' ' ')
          echo "all_changed_files=$files" >> $GITHUB_OUTPUT
          echo "any_changed=true" >> $GITHUB_OUTPUT

      - name: Prepare matrix
        id: prep_matrix
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            files="${{ steps.all_workflows.outputs.all_changed_files }}"
          else
            files="${{ steps.detect.outputs.all_changed_files }}"
          fi
          
          json="["
          sep=""
          for f in $files; do
            base=$(basename "$f" .yml)
            json="${json}${sep}{\"workflow\":\"$f\",\"basename\":\"$base\"}"
            sep=","
          done
          json="${json}]"
          echo "matrix=$json" >> $GITHUB_OUTPUT

      - name: Handle matrix
        id: handle_matrix
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            any_changed="${{ steps.all_workflows.outputs.any_changed }}"
          else
            any_changed="${{ steps.detect.outputs.any_changed }}"
          fi
          
          if [ "$any_changed" = "false" ]; then
            echo 'matrix={"include":[]}' >> $GITHUB_OUTPUT
            echo 'has_changes=false' >> $GITHUB_OUTPUT
          else
            echo 'matrix={"include":${{ steps.prep_matrix.outputs.matrix }}}' >> $GITHUB_OUTPUT
            echo 'has_changes=true' >> $GITHUB_OUTPUT
          fi

      - name: Get PR source branch
        id: get_source_branch
        run: |
          echo "pr_source_branch=${{ github.head_ref || github.ref_name }}" >> $GITHUB_OUTPUT

  update-doc:
    if: needs.detect-changes.outputs.has_changes == 'true'
    needs: detect-changes
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.detect-changes.outputs.matrix) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Ensure docs folder
        run: mkdir -p docs

      - name: Auto-doc for workflow
        uses: tj-actions/auto-doc@v3
        with:
          filename: ./${{ matrix.workflow }}
          reusable: true
          output: docs/README-${{ matrix.basename }}.md
          inputs: true
          outputs: true
          steps: detailed
          include_html: true
          use_code_blocks: true
          markdown_links: true
          markdown_format: rich
          badges: true
          col_max_width: 200
          col_max_words: 999

      - name: Check if README was created or modified
        id: check_changes
        run: |
          git add docs/README-${{ matrix.basename }}.md
          if git diff --cached --quiet; then
            echo "has_changes=false" >> $GITHUB_OUTPUT
          else
            echo "has_changes=true" >> $GITHUB_OUTPUT
          fi

      - name: Create Pull Request for Documentation Update
        if: steps.check_changes.outputs.has_changes == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "docs: auto-update README for ${{ matrix.basename }}"
          title: "docs: auto-update README for ${{ matrix.basename }}"
          body: "This PR auto-updates the documentation for workflow `${{ matrix.basename }}`."
          branch: "auto-doc/update-readme-${{ matrix.basename }}"
          token: ${{ secrets.GITHUB_TOKEN }}
          base: ${{ needs.detect-changes.outputs.pr_source_branch }}
