name: Generate Workflow Documentation

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/**'
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install pyyaml

      - name: List all workflows
        run: |
          echo "=== All workflow files ==="
          find .github/workflows -name "*.yml" -o -name "*.yaml"
          echo "=========================="

      - name: Generate documentation
        run: |
          mkdir -p docs
          
          cat > generate_docs.py << 'EOF'
          import yaml
          import sys
          from pathlib import Path
          from datetime import datetime

          def generate_workflow_doc(workflow_path):
              print(f"Processing: {workflow_path}")
              
              try:
                  with open(workflow_path, 'r') as f:
                      workflow = yaml.safe_load(f)
              except Exception as e:
                  print(f"❌ Failed to parse {workflow_path}: {e}")
                  return None
              
              if not workflow:
                  print(f"⚠️ Empty workflow file: {workflow_path}")
                  return None
              
              basename = Path(workflow_path).stem
              doc_path = f"docs/README-{basename}.md"
              workflow_name = workflow.get('name', basename)
              
              # Start building documentation with beautiful header
              doc = f"<div align=\"center\">\n\n"
              doc += f"# 🚀 {workflow_name}\n\n"
              doc += f"![Auto-generated](https://img.shields.io/badge/docs-auto--generated-blue?style=flat-square)\n"
              doc += f"![Workflow](https://img.shields.io/badge/type-github--workflow-purple?style=flat-square)\n"
              doc += f"![Updated](https://img.shields.io/badge/updated-{datetime.now().strftime('%Y.%m.%d')}-green?style=flat-square)\n\n"
              doc += f"</div>\n\n"
              doc += "---\n\n"
              doc += "## 📋 Overview\n\n"
              doc += f"> **Workflow File:** `.github/workflows/{Path(workflow_path).name}`\n\n"
              
              # Trigger information with better formatting
              doc += "## ⚡ Triggers\n\n"
              doc += "<table>\n<tr><th>Event</th><th>Details</th></tr>\n"
              
              if 'on' in workflow:
                  triggers = workflow['on']
                  if isinstance(triggers, dict):
                      for trigger, config in triggers.items():
                          details = []
                          
                          if trigger == 'workflow_call':
                              doc += f"<tr><td><code>🔄 {trigger}</code></td><td><em>Reusable workflow</em></td></tr>\n"
                          elif isinstance(config, dict):
                              if 'branches' in config:
                                  branches = config['branches']
                                  if isinstance(branches, list):
                                      details.append(f"<strong>Branches:</strong> <code>{', '.join(branches)}</code>")
                              if 'paths' in config:
                                  paths = config['paths']
                                  if isinstance(paths, list):
                                      details.append(f"<strong>Paths:</strong> <code>{', '.join(paths)}</code>")
                              
                              detail_text = '<br>'.join(details) if details else '<em>No filters</em>'
                              doc += f"<tr><td><code>⚡ {trigger}</code></td><td>{detail_text}</td></tr>\n"
                          else:
                              doc += f"<tr><td><code>⚡ {trigger}</code></td><td><em>Standard trigger</em></td></tr>\n"
                  elif isinstance(triggers, list):
                      for trigger in triggers:
                          doc += f"<tr><td><code>⚡ {trigger}</code></td><td><em>Standard trigger</em></td></tr>\n"
                  else:
                      doc += f"<tr><td><code>⚡ {triggers}</code></td><td><em>Standard trigger</em></td></tr>\n"
              else:
                  doc += "<tr><td colspan='2'><em>No triggers defined</em></td></tr>\n"
              
              doc += "</table>\n\n"
              
              # Inputs/Outputs for reusable workflows with prettier tables
              if 'on' in workflow and isinstance(workflow['on'], dict) and 'workflow_call' in workflow['on']:
                  call_config = workflow['on']['workflow_call']
                  
                  # Inputs
                  if 'inputs' in call_config and call_config['inputs']:
                      doc += "## 📥 Inputs\n\n"
                      doc += "<table>\n"
                      doc += "<thead>\n<tr>\n<th>Parameter</th>\n<th>Type</th>\n<th>Required</th>\n<th>Default</th>\n<th>Description</th>\n</tr>\n</thead>\n"
                      doc += "<tbody>\n"
                      
                      for name, config in call_config['inputs'].items():
                          required = '✅' if config.get('required', False) else '❌'
                          input_type = config.get('type', 'string')
                          default = config.get('default', '—')
                          description = config.get('description', 'No description provided')
                          
                          doc += f"<tr>\n"
                          doc += f"<td><code>{name}</code></td>\n"
                          doc += f"<td><code>{input_type}</code></td>\n"
                          doc += f"<td align='center'>{required}</td>\n"
                          doc += f"<td><code>{default}</code></td>\n"
                          doc += f"<td>{description}</td>\n"
                          doc += f"</tr>\n"
                      
                      doc += "</tbody>\n</table>\n\n"
                  
                  # Outputs
                  if 'outputs' in call_config and call_config['outputs']:
                      doc += "## 📤 Outputs\n\n"
                      doc += "<table>\n"
                      doc += "<thead>\n<tr>\n<th>Output</th>\n<th>Description</th>\n<th>Value</th>\n</tr>\n</thead>\n"
                      doc += "<tbody>\n"
                      
                      for name, config in call_config['outputs'].items():
                          description = config.get('description', 'No description provided')
                          value = config.get('value', 'N/A')
                          
                          doc += f"<tr>\n"
                          doc += f"<td><code>{name}</code></td>\n"
                          doc += f"<td>{description}</td>\n"
                          doc += f"<td><code>{value}</code></td>\n"
                          doc += f"</tr>\n"
                      
                      doc += "</tbody>\n</table>\n\n"
              
              # Jobs with collapsible sections for cleaner view
              if 'jobs' in workflow and workflow['jobs']:
                  doc += "## 🔨 Jobs\n\n"
                  
                  for job_name, job_config in workflow['jobs'].items():
                      doc += f"### 🎯 `{job_name}`\n\n"
                      
                      # Job metadata
                      metadata = []
                      if 'runs-on' in job_config:
                          metadata.append(f"**🖥️ Runner:** `{job_config['runs-on']}`")
                      if 'uses' in job_config:
                          metadata.append(f"**📞 Calls:** `{job_config['uses']}`")
                      
                      if metadata:
                          doc += ' | '.join(metadata) + "\n\n"
                      
                      # Job outputs
                      if 'outputs' in job_config:
                          doc += "<details>\n<summary>📊 Job Outputs</summary>\n\n"
                          doc += "```yaml\n"
                          for out_name, out_val in job_config['outputs'].items():
                              doc += f"{out_name}: {out_val}\n"
                          doc += "```\n\n"
                          doc += "</details>\n\n"
                      
                      # Steps in a collapsible section
                      if 'steps' in job_config and job_config['steps']:
                          doc += "<details>\n<summary>📝 Steps</summary>\n\n"
                          
                          for i, step in enumerate(job_config['steps'], 1):
                              step_name = step.get('name', f'Step {i}')
                              doc += f"#### {i}. {step_name}\n\n"
                              
                              if 'uses' in step:
                                  doc += f"```yaml\n"
                                  doc += f"uses: {step['uses']}\n"
                                  if 'with' in step:
                                      doc += f"with:\n"
                                      for key, val in list(step['with'].items())[:5]:
                                          val_str = str(val).replace('\n', ' ')
                                          if len(val_str) > 60:
                                              val_str = val_str[:60] + "..."
                                          doc += f"  {key}: {val_str}\n"
                                  doc += f"```\n\n"
                              
                              if 'run' in step:
                                  run_cmd = step['run'].strip()
                                  lines = run_cmd.split('\n')
                                  if len(lines) > 5:
                                      run_cmd = '\n'.join(lines[:5]) + '\n# ... (truncated)'
                                  doc += f"```bash\n{run_cmd}\n```\n\n"
                          
                          doc += "</details>\n\n"
              
              # Usage example for reusable workflows with syntax highlighting
              if 'on' in workflow and isinstance(workflow['on'], dict) and 'workflow_call' in workflow['on']:
                  doc += "## 📖 Usage Example\n\n"
                  doc += "> Copy this example into your workflow file to use this reusable workflow:\n\n"
                  doc += "```yaml\n"
                  doc += f"name: My Workflow\n\n"
                  doc += "on: [push]\n\n"
                  doc += "jobs:\n"
                  doc += f"  call-{basename}:\n"
                  doc += f"    uses: ./.github/workflows/{Path(workflow_path).name}\n"
                  
                  call_config = workflow['on']['workflow_call']
                  if 'inputs' in call_config and call_config['inputs']:
                      doc += "    with:\n"
                      for input_name, input_config in call_config['inputs'].items():
                          default = input_config.get('default', 'your-value-here')
                          doc += f"      {input_name}: {default}\n"
                  doc += "```\n\n"
                  
                  # Add output usage if there are outputs
                  if 'outputs' in call_config and call_config['outputs']:
                      doc += "### Using Outputs\n\n"
                      doc += "```yaml\n"
                      doc += "jobs:\n"
                      doc += f"  call-{basename}:\n"
                      doc += f"    uses: ./.github/workflows/{Path(workflow_path).name}\n"
                      doc += "\n"
                      doc += "  use-outputs:\n"
                      doc += f"    needs: call-{basename}\n"
                      doc += "    runs-on: ubuntu-latest\n"
                      doc += "    steps:\n"
                      for output_name in call_config['outputs'].keys():
                          doc += f"      - name: Use {output_name}\n"
                          doc += f"        run: echo \"Output: ${{{{ needs.call-{basename}.outputs.{output_name} }}}}\"\n"
                      doc += "```\n\n"
              
              doc += "---\n\n"
              doc += "<div align=\"center\">\n\n"
              doc += "**📅 Last Updated:** " + datetime.now().strftime('%B %d, %Y at %H:%M UTC') + "\n\n"
              doc += "*This documentation is automatically generated. Manual edits will be overwritten.*\n\n"
              doc += "</div>\n"
              
              # Write the documentation
              try:
                  with open(doc_path, 'w') as f:
                      f.write(doc)
                  print(f"✅ Generated: {doc_path}")
                  return doc_path
              except Exception as e:
                  print(f"❌ Failed to write {doc_path}: {e}")
                  return None

          if __name__ == "__main__":
              # Get all workflow files
              import glob
              
              workflow_files = glob.glob('.github/workflows/*.yml') + glob.glob('.github/workflows/*.yaml')
              
              # Filter out the doc generator itself
              workflow_files = [wf for wf in workflow_files if 'workflow-doc-generator' not in wf and 'doc-gen' not in wf]
              
              print(f"Found {len(workflow_files)} workflow files to process")
              
              generated = []
              for wf in workflow_files:
                  doc = generate_workflow_doc(wf)
                  if doc:
                      generated.append(doc)
              
              print(f"\n✅ Successfully generated {len(generated)} documentation files")
              
              # Save list of generated files
              with open('generated_docs.txt', 'w') as f:
                  f.write('\n'.join(generated))
          EOF
          
          python generate_docs.py

      - name: Show generated docs
        run: |
          echo "==== GENERATED DOCUMENTATION ===="
          for file in docs/README-*.md; do
            if [ -f "$file" ]; then
              echo ""
              echo "📄 $file"
              echo "---"
              cat "$file"
              echo ""
              echo "================================="
            fi
          done

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "docs: auto-generate workflow documentation"
          title: "📝 Update Workflow Documentation"
          body: |
            ## 🤖 Auto-generated Documentation Update
            
            This PR contains automatically generated documentation for all workflows.
            
            ### 📄 Generated Docs
            Check the `docs/` folder for updated README files.
            
            ---
            *This is an automated PR. Review before merging.*
          branch: docs/workflow-update-${{ github.run_number }}
          delete-branch: true
          labels: |
            documentation
            automated
