name: Generate Workflow Documentation (Debug)

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Debug - Check repo structure
        run: |
          echo "=== Repository Structure ==="
          ls -la
          echo ""
          echo "=== Workflow files ==="
          ls -la .github/workflows/
          echo ""
          echo "=== Current docs folder ==="
          ls -la docs/ 2>/dev/null || echo "docs/ doesn't exist yet"

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          echo "Installing PyYAML..."
          pip install pyyaml
          echo "Done!"

      - name: Debug - List all workflows
        run: |
          echo "=== Finding workflow files ==="
          find .github/workflows -type f \( -name "*.yml" -o -name "*.yaml" \)
          echo ""
          echo "=== Counting workflows ==="
          find .github/workflows -type f \( -name "*.yml" -o -name "*.yaml" \) | wc -l

      - name: Debug - Test Python and PyYAML
        run: |
          echo "Testing Python..."
          python --version
          echo ""
          echo "Testing PyYAML import..."
          python -c "import yaml; print('PyYAML version:', yaml.__version__)"
          echo ""
          echo "Testing workflow parsing..."
          python -c "
          import yaml
          with open('.github/workflows/build-jar.yml', 'r') as f:
              wf = yaml.safe_load(f)
              print('Workflow name:', wf.get('name', 'N/A'))
              print('Has jobs:', 'jobs' in wf)
          "

      - name: Generate documentation
        run: |
          mkdir -p docs
          
          cat > generate_docs.py << 'END_OF_PYTHON'
          import yaml
          import sys
          from pathlib import Path
          from datetime import datetime
          import traceback

          def generate_workflow_doc(workflow_path):
              print(f"\n{'='*60}")
              print(f"Processing: {workflow_path}")
              print(f"{'='*60}")
              
              try:
                  with open(workflow_path, 'r') as f:
                      workflow = yaml.safe_load(f)
                  print(f"✓ Successfully parsed YAML")
              except Exception as e:
                  print(f"✗ Failed to parse {workflow_path}")
                  print(f"Error: {e}")
                  traceback.print_exc()
                  return None
              
              if not workflow:
                  print(f"✗ Empty workflow file: {workflow_path}")
                  return None
              
              print(f"✓ Workflow has {len(workflow.get('jobs', {}))} jobs")
              
              basename = Path(workflow_path).stem
              doc_path = f"docs/README-{basename}.md"
              workflow_name = workflow.get('name', basename)
              
              print(f"✓ Generating doc: {doc_path}")
              
              # Start building documentation
              doc = f"<div align=\"center\">\n\n"
              doc += f"# 🚀 {workflow_name}\n\n"
              doc += f"![Auto-generated](https://img.shields.io/badge/docs-auto--generated-blue?style=flat-square)\n"
              doc += f"![Workflow](https://img.shields.io/badge/type-github--workflow-purple?style=flat-square)\n"
              doc += f"![Updated](https://img.shields.io/badge/updated-{datetime.now().strftime('%Y.%m.%d')}-green?style=flat-square)\n\n"
              doc += f"</div>\n\n"
              doc += "---\n\n"
              doc += "## 📋 Overview\n\n"
              doc += f"> **Workflow File:** `.github/workflows/{Path(workflow_path).name}`\n\n"
              
              # Trigger information
              doc += "## ⚡ Triggers\n\n"
              doc += "<table>\n<tr><th>Event</th><th>Details</th></tr>\n"
              
              if 'on' in workflow:
                  triggers = workflow['on']
                  if isinstance(triggers, dict):
                      for trigger, config in triggers.items():
                          if trigger == 'workflow_call':
                              doc += f"<tr><td><code>🔄 {trigger}</code></td><td><em>Reusable workflow</em></td></tr>\n"
                          elif isinstance(config, dict):
                              details = []
                              if 'branches' in config and isinstance(config['branches'], list):
                                  details.append(f"<strong>Branches:</strong> <code>{', '.join(config['branches'])}</code>")
                              if 'paths' in config and isinstance(config['paths'], list):
                                  details.append(f"<strong>Paths:</strong> <code>{', '.join(config['paths'])}</code>")
                              detail_text = '<br>'.join(details) if details else '<em>No filters</em>'
                              doc += f"<tr><td><code>⚡ {trigger}</code></td><td>{detail_text}</td></tr>\n"
                          else:
                              doc += f"<tr><td><code>⚡ {trigger}</code></td><td><em>Standard trigger</em></td></tr>\n"
                  else:
                      doc += f"<tr><td><code>⚡ {triggers}</code></td><td><em>Standard trigger</em></td></tr>\n"
              else:
                  doc += "<tr><td colspan='2'><em>No triggers defined</em></td></tr>\n"
              
              doc += "</table>\n\n"
              
              # Inputs/Outputs for reusable workflows
              call_config = None

              on_section = workflow.get("on", {})

              # Case 1: "on:" is a dict (most common)
              if isinstance(on_section, dict):
                  call_config = on_section.get("workflow_call")

              # Case 2: "on:" is a list (rare)
              elif isinstance(on_section, list):
                  for item in on_section:
                      if isinstance(item, dict) and "workflow_call" in item:
                          call_config = item["workflow_call"]
                          break

              # Normalize to empty dict so lookups succeed
              if call_config is None:
                  call_config = {}

              # --- INPUTS ---
              if "inputs" in call_config and call_config["inputs"]:
                  doc += "## 📥 Inputs\n\n"
                  doc += "<table>\n<thead>\n<tr>\n<th>Parameter</th>\n<th>Type</th>\n<th>Required</th>\n<th>Default</th>\n<th>Description</th>\n</tr>\n</thead>\n<tbody>\n"

                  for name, config in call_config["inputs"].items():
                      if not isinstance(config, dict):
                          config = {"type": "string", "required": False, "default": config}

                      required = "✅" if config.get("required", False) else "❌"
                      input_type = config.get("type", "string")
                      default_val = config.get("default", "—") or "—"
                      description = config.get("description", "<em>No description provided</em>")

                      doc += (
                          f"<tr>"
                          f"<td><code>{name}</code></td>"
                          f"<td><code>{input_type}</code></td>"
                          f"<td align='center'>{required}</td>"
                          f"<td><code>{default_val}</code></td>"
                          f"<td>{description}</td>"
                          f"</tr>\n"
                      )

                  doc += "</tbody></table>\n\n"

              # --- OUTPUTS ---
              if "outputs" in call_config and call_config["outputs"]:
                  doc += "## 📤 Outputs\n\n"
                  doc += "<table>\n<thead>\n<tr>\n<th>Output</th>\n<th>Description</th>\n<th>Value</th>\n</tr>\n</thead>\n<tbody>\n"

                  for name, config in call_config["outputs"].items():
                      description = config.get("description", "No description provided")
                      value = config.get("value", "N/A")

                      doc += (
                          f"<tr>"
                          f"<td><code>{name}</code></td>"
                          f"<td>{description}</td>"
                          f"<td><code>{value}</code></td>"
                          f"</tr>\n"
                      )

                  doc += "</tbody></table>\n\n"


              # Jobs
              if 'jobs' in workflow and workflow['jobs']:
                  doc += "## 🔨 Jobs\n\n"
                  
                  for job_name, job_config in workflow['jobs'].items():
                      doc += f"### 🎯 `{job_name}`\n\n"
                      
                      metadata = []
                      if 'runs-on' in job_config:
                          metadata.append(f"**🖥️ Runner:** `{job_config['runs-on']}`")
                      if 'uses' in job_config:
                          metadata.append(f"**📞 Calls:** `{job_config['uses']}`")
                      
                      if metadata:
                          doc += ' | '.join(metadata) + "\n\n"
                      
                      if 'outputs' in job_config:
                          doc += "<details>\n<summary>📊 Job Outputs</summary>\n\n```yaml\n"
                          for out_name, out_val in job_config['outputs'].items():
                              doc += f"{out_name}: {out_val}\n"
                          doc += "```\n\n</details>\n\n"
                      
                      if 'steps' in job_config and job_config['steps']:
                          doc += "<details>\n<summary>📝 Steps</summary>\n\n"
                          
                          for i, step in enumerate(job_config['steps'], 1):
                              step_name = step.get('name', f'Step {i}')
                              doc += f"#### {i}. {step_name}\n\n"
                              
                              if 'uses' in step:
                                  doc += f"```yaml\nuses: {step['uses']}\n"
                                  if 'with' in step:
                                      doc += f"with:\n"
                                      for key, val in list(step['with'].items())[:5]:
                                          val_str = str(val).replace('\n', ' ')
                                          if len(val_str) > 60:
                                              val_str = val_str[:60] + "..."
                                          doc += f"  {key}: {val_str}\n"
                                  doc += f"```\n\n"
                              
                              if 'run' in step:
                                  run_cmd = step['run'].strip()
                                  lines = run_cmd.split('\n')
                                  if len(lines) > 5:
                                      run_cmd = '\n'.join(lines[:5]) + '\n# ... (truncated)'
                                  doc += f"```bash\n{run_cmd}\n```\n\n"
                          
                          doc += "</details>\n\n"
              
              # Usage example
              if 'on' in workflow and isinstance(workflow['on'], dict) and 'workflow_call' in workflow['on']:
                  doc += "## 📖 Usage Example\n\n"
                  doc += "> Copy this example into your workflow file:\n\n"
                  doc += "```yaml\n"
                  doc += f"name: My Workflow\n\non: [push]\n\njobs:\n  call-{basename}:\n"
                  doc += f"    uses: ./.github/workflows/{Path(workflow_path).name}\n"
                  
                  call_config = workflow['on']['workflow_call']
                  if 'inputs' in call_config and call_config['inputs']:
                      doc += "    with:\n"
                      for input_name, input_config in call_config['inputs'].items():
                          default = input_config.get('default', 'your-value-here')
                          doc += f"      {input_name}: {default}\n"
                  doc += "```\n\n"
              
              doc += "---\n\n"
              doc += "<div align=\"center\">\n\n"
              doc += "**📅 Last Updated:** " + datetime.now().strftime('%B %d, %Y at %H:%M UTC') + "\n\n"
              doc += "*Auto-generated documentation. Manual edits will be overwritten.*\n\n"
              doc += "</div>\n"
              
              # Write the file
              try:
                  with open(doc_path, 'w') as f:
                      f.write(doc)
                  print(f"✓ Successfully wrote: {doc_path}")
                  print(f"✓ File size: {len(doc)} bytes")
                  return doc_path
              except Exception as e:
                  print(f"✗ Failed to write {doc_path}")
                  print(f"Error: {e}")
                  traceback.print_exc()
                  return None

          if __name__ == "__main__":
              import glob
              
              print("Starting documentation generation...")
              print()
              
              workflow_files = glob.glob('.github/workflows/*.yml') + glob.glob('.github/workflows/*.yaml')
              workflow_files = [wf for wf in workflow_files if 'workflow-doc-generator' not in wf and 'doc-gen' not in wf]
              
              print(f"Found {len(workflow_files)} workflow files:")
              for wf in workflow_files:
                  print(f"  - {wf}")
              print()
              
              generated = []
              failed = []
              
              for wf in workflow_files:
                  doc = generate_workflow_doc(wf)
                  if doc:
                      generated.append(doc)
                  else:
                      failed.append(wf)
              
              print(f"\n{'='*60}")
              print(f"SUMMARY")
              print(f"{'='*60}")
              print(f"✓ Successfully generated: {len(generated)} files")
              print(f"✗ Failed: {len(failed)} files")
              
              if generated:
                  print(f"\nGenerated files:")
                  for doc in generated:
                      print(f"  ✓ {doc}")
              
              if failed:
                  print(f"\nFailed files:")
                  for wf in failed:
                      print(f"  ✗ {wf}")
              
              with open('generated_docs.txt', 'w') as f:
                  f.write('\n'.join(generated))
          END_OF_PYTHON
          
          echo "Running documentation generator..."
          python generate_docs.py

      - name: Show generated docs
        run: |
          echo "==== GENERATED DOCUMENTATION ===="
          for file in docs/README-*.md; do
            if [ -f "$file" ]; then
              echo ""
              echo "📄 $file"
              echo "--- First 50 lines ---"
              head -n 50 "$file"
              echo ""
              echo "--- File size ---"
              wc -l "$file"
              echo "================================="
            fi
          done

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "docs: auto-generate workflow documentation"
          title: "📝 Update Workflow Documentation (Debug)"
          body: |
            ## 🤖 Debug Documentation Update
            
            This is a debug run to see what's being generated.
            
            Check the workflow logs and generated files.
          branch: docs/workflow-debug-${{ github.run_number }}
          delete-branch: true
