name: ðŸ“ Auto-generate workflow READMEs v5

on:
  workflow_dispatch:
#  pull_request:
#    paths:
 #     - ".github/workflows/*.yml"

permissions:
  contents: write
  pull-requests: write

env:
  GITHUB_USER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GITHUB_USER_EMAIL: ${{ github.actor }}@users.noreply.github.com
  GITHUB_USER_NAME: ${{ github.actor }}

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.handle_matrix.outputs.matrix }}
      has_changes: ${{ steps.handle_matrix.outputs.has_changes }}
      pr_source_branch: ${{ steps.get_source_branch.outputs.pr_source_branch }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Detect changed workflow files
        id: detect
        uses: tj-actions/changed-files@v44
        with:
          files: |
            .github/workflows/*.yml
            !.github/workflows/workflow_docs_v2.yml

      - name: Prepare matrix
        id: prep_matrix
        run: |
          files="${{ steps.detect.outputs.all_changed_files }}"
          json="["
          sep=""
          for f in $files; do
            base=$(basename "$f" .yml)
            json="${json}${sep}{\"workflow\":\"$f\",\"basename\":\"$base\"}"
            sep=","
          done
          json="${json}]"
          echo "matrix=$json" >> $GITHUB_OUTPUT

      - name: Handle empty matrix
        id: handle_matrix
        run: |
          if [ "${{ steps.detect.outputs.any_changed }}" = "false" ]; then
            echo 'matrix={"include":[]}' >> $GITHUB_OUTPUT
            echo 'has_changes=false' >> $GITHUB_OUTPUT
          else
            echo 'matrix={"include":${{ steps.prep_matrix.outputs.matrix }}}' >> $GITHUB_OUTPUT
            echo 'has_changes=true' >> $GITHUB_OUTPUT
          fi

      - name: Get PR source branch
        id: get_source_branch
        run: |
          echo "pr_source_branch=${{ github.head_ref || github.ref_name }}" >> $GITHUB_OUTPUT

  update-doc:
    if: needs.detect-changes.outputs.has_changes == 'true'
    needs: detect-changes
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.detect-changes.outputs.matrix) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Ensure docs folder
        run: mkdir -p docs

      - name: Auto-doc for workflow
        uses: tj-actions/auto-doc@v3
        with:
          filename: ./${{ matrix.workflow }}
          reusable: true
          output: docs/README-${{ matrix.basename }}.md
          inputs: true
          outputs: true
          steps: detailed
          include_html: true
          use_code_blocks: true
          markdown_links: true
          markdown_format: rich
          badges: true
          col_max_width: 200
          col_max_words: 999

      - name: Verify changed README
        id: verify
        uses: tj-actions/verify-changed-files@v19
        with:
          files: docs/README-${{ matrix.basename }}.md

      - name: Create Pull Request for Documentation Update
        if: steps.verify.outputs.files_changed == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "docs: auto-update README for ${{ matrix.basename }}"
          title: "docs: auto-update README for ${{ matrix.basename }}"
          body: "This PR auto-updates the documentation for workflow `${{ matrix.basename }}`."
          branch: "auto-doc/update-readme-${{ matrix.basename }}"
          token: ${{ env.GITHUB_USER_TOKEN }}
          committer: ${{ env.GITHUB_USER_NAME }} <${{ env.GITHUB_USER_EMAIL }}>
          base: ${{ needs.detect-changes.outputs.pr_source_branch }}
